name: 'Token Tinker'
description: 'Transform design tokens from Tokens Studio using Style Dictionary'
branding:
  icon: 'command'
  color: 'gray-dark'
inputs:
  tokens-path:
    description: 'Path to the tokens json files. Defaults to ./tokens/'
    required: true
    default: './tokens/'
  build-path:
    description: 'Path to output the transformed tokens. Defaults to ./build/'
    required: true
    default: './build/'
  tokens-export-type:
    description: 'Type of Tokens Studio export: "single" for single file or "multiple" for multiple files.'
    required: false
    default: 'single'
runs:
  using: 'node20'
  main: 'dist/index.js'